// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 1DV507 -- Programming and Data Structures, VT2017
// Assignment 2: Data Structures, JUnit, and JavaFX1
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Created by Jonas Sjöberg (js224eh) on 2017-02-06.

package js224eh_assign2.queue;


import java.util.Iterator;

/*
 * Exercise 1
 * ==========
 * A Queue is a FIFO (first in, first out) data structure.
 * Consider the following queue interface:
 */

public interface Queue
{
    /**
     * Gets the current size of the queue, I.E. the number of enqueued elements.
     *
     * @return The number of elements stored in this queue.
     */
    public int size();

    /**
     * Returns whether the queue is empty or not.
     *
     * @return True if this queue is empty, otherwise False.
     */
    public boolean isEmpty();

    /**
     * Adds an element to the queue. The element is added to the back of
     * the queue; FIFO -- First In First Out.
     *
     * @param element The element to add to this queue.
     */
    public void enqueue(Object element);

    /**
     * Removes an element from the queue. The element that was enqueued first
     * is returned; FIFO -- First In First Out.
     *
     * @return The next element in line in this queue.
     */
    public Object dequeue();

    /**
     * Returns the first element of the queue, without removing it.
     *
     * @return The first element in this queue.
     */
    public Object first();

    /**
     * Returns the last element of the queue, without removing it.
     *
     * @return The last element in this queue.
     */
    public Object last();

    /**
     * Returns a human readable textual representation of the queue.
     *
     * @return A string representation of this queue.
     */
    public String toString();

    /**
     * Returns an element iterator for the queue.
     *
     * @return An element iterator for this queue.
     */
    public Iterator<Object> iterator();
}

/*
 * The iterator iterates over all elements of the queue. Operations not
 * allowed on an empty queue shall generate an unchecked exception.
 *
 * Tasks:
 * - Create a linked implementation LinkedQueue.java of the interface Queue.
 *   Use the head-and-tail approach.
 * - Write also a program QueueMain.java showing how all methods work.
 * - Create Javadoc comments in the code and generate good-looking and
 *   extensive HTML documentation for the interface and the class.
 *   All public class members shall be documented.
 *
 * Notice:
 * - The implementation shall be linked, i.e. a sequence of linked nodes
 *   where each node represents an element.
 * - You are not allowed to use any of the predefined collection classes in
 *   the Java library.
 * - In the report, the HTML pages generated by the classes Queue and
 *   LinkedQueue shall be attached. Attach no other HTML pages!
 */