// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 1DV507 -- Programming and Data Structures, VT2017
// Assignment 2: Data Structures, JUnit, and JavaFX1
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Created by Jonas Sjöberg (js224eh) on 2017-02-06.

package js224eh_assign2.queue;


import java.util.Iterator;

/*
 * Exercise 1
 * ==========
 * A Queue is a FIFO (first in, first out) data structure.
 * Consider the following queue interface:
 */

public interface Queue
{
    public int size();                     // current queue size

    public boolean isEmpty();              // true if queue is empty

    public void enqueue(Object element);   // add element at end of queue

    public Object dequeue();               // return and remove first element.

    public Object first();                 // return (without removing) first
                                           // element
    public Object last();                  // return (without removing) last
                                           // element
    public String toString();              // return a string representation
                                           // of the queue content
    public Iterator<Object> iterator();    // element iterator
}

/*
 * The iterator iterates over all elements of the queue. Operations not
 * allowed on an empty queue shall generate an unchecked exception.
 *
 * Tasks:
 * - Create a linked implementation LinkedQueue.java of the interface Queue.
 *   Use the head-and-tail approach.
 * - Write also a program QueueMain.java showing how all methods work.
 * - Create Javadoc comments in the code and generate good-looking and
 *   extensive HTML documentation for the interface and the class.
 *   All public class members shall be documented.
 *
 * Notice:
 * - The implementation shall be linked, i.e. a sequence of linked nodes
 *   where each node represents an element.
 * - You are not allowed to use any of the predefined collection classes in
 *   the Java library.
 * - In the report, the HTML pages generated by the classes Queue and
 *   LinkedQueue shall be attached. Attach no other HTML pages!
 */